### PR TITLE
First UE-NIB reader API description

### PR DESCRIPTION
**Pull request by tietavai**
Add first version of UE-NIB reader API descriptions to query UE state,
SpCell, MeNb UE X2AP ID, SgNb UE X2 AP ID, UE bearers and bearer S1 UL
tunnel endpoint. Also added a draft version of event interface to
register an event receiver for Dual Connectivity change events.

### CODE REVIEW

**Comment by tietavai** [comment]
@makiaija @CsatariGergely For review

**Comment by tietavai** [comment]
Added also @imraan

**Comment by mohammedimraan** [comment]
Adding Comments as discussed in Jabber with Timo Just for Reference:
1. What is the content of cell information?
Ans)GetSpCell() API returns "object/structure" of type:
type Cell struct {
        Pci     uint32 //Physical cell ID
        SsbFreq uint32 //Frequency of the SSB to be used for the serving cell.
}

2. Can QCI/ARP Entries for the RAB be obtained?
Ans) Will Check for the feasibility for the same and implement if smaller effort. 
proposal is to query and get the same:
GetBearerERABQCI(UEID, BearerID)
GetBearerArp(UEID, BearerID)

3. What are all the possible States of the UE?
Ans)GetState() API returns value of type:
type UeState struct {
        Event     string
        Timestamp string
}
Event string probably contains information about lastly received X2 message and maybe at reject case the cause code. We haven't yet fully planned event string content.

**Comment by tietavai** [comment]
> 
> 
> Adding Comments as discussed in Jabber with Timo Just for Reference:
> 
>     1. What is the content of cell information?
>        Ans)GetSpCell() API returns "object/structure" of type:
>        type Cell struct {
>        Pci     uint32 //Physical cell ID
>        SsbFreq uint32 //Frequency of the SSB to be used for the serving cell.
>        }
> 
>     2. Can QCI/ARP Entries for the RAB be obtained?
>        Ans) Will Check for the feasibility for the same and implement if smaller effort.
>        proposal is to query and get the same:
>        GetBearerERABQCI(UEID, BearerID)
>        GetBearerArp(UEID, BearerID)
> 
>     3. What are all the possible States of the UE?
>        Ans)GetState() API returns value of type:
>        type UeState struct {
>        Event     string
>        Timestamp string
>        }
>        Event string probably contains information about lastly received X2 message and maybe at reject case the cause code. We haven't yet fully planned event string content.

Comment about second item (2. Can QCI/ARP Entries for the RAB be obtained?)
Are you sure that you need all the ARP entries?
Would it be enough to return only:
QCI, ARP: <PRIORITY_LEVEL, PREEMPTION_CAPABILITY, PREEMPTION_VULNERABILITY>
Or do you really need also Quaranteed Bit Rate ARP values too:
<MBR_DL, MBR_UL, GBR_DL, GBR_UL>

Trying to minimize the UE-NIB work effort, that's why I'm asking this?
Thanks,
Timo

**Comment by mohammedimraan** [comment]
> > Adding Comments as discussed in Jabber with Timo Just for Reference:
> > ```
> > 1. What is the content of cell information?
> >    Ans)GetSpCell() API returns "object/structure" of type:
> >    type Cell struct {
> >    Pci     uint32 //Physical cell ID
> >    SsbFreq uint32 //Frequency of the SSB to be used for the serving cell.
> >    }
> > 
> > 2. Can QCI/ARP Entries for the RAB be obtained?
> >    Ans) Will Check for the feasibility for the same and implement if smaller effort.
> >    proposal is to query and get the same:
> >    GetBearerERABQCI(UEID, BearerID)
> >    GetBearerArp(UEID, BearerID)
> > 
> > 3. What are all the possible States of the UE?
> >    Ans)GetState() API returns value of type:
> >    type UeState struct {
> >    Event     string
> >    Timestamp string
> >    }
> >    Event string probably contains information about lastly received X2 message and maybe at reject case the cause code. We haven't yet fully planned event string content.
> > ```
> 
> Comment about second item (2. Can QCI/ARP Entries for the RAB be obtained?)
> Are you sure that you need all the ARP entries?
> Would it be enough to return only:
> QCI, ARP: <PRIORITY_LEVEL, PREEMPTION_CAPABILITY, PREEMPTION_VULNERABILITY>
> Or do you really need also Quaranteed Bit Rate ARP values too:
> <MBR_DL, MBR_UL, GBR_DL, GBR_UL>
> 
> Trying to minimize the UE-NIB work effort, that's why I'm asking this?
> Thanks,
> Timo

For Now then to simplify not all are needed, if you can provide only Allocation and Retention Priority level that should be sufficient.

Regards,
Imraan

**Comment by tietavai** [comment]
Following new query APIs added to query bearer QCI and ARP PL values:
`GetQosQCI(ueID *uenib.UeID, bID uenib.BearerID) (uint32, error)`
`GetQosArpPL(ueID *uenib.UeID, bID uenib.BearerID) (uint32, error)`

**Review by CsatariGergely — APPROVED** [review]

**Review by oruotsal — APPROVED** [review]

**Pull request merged**
